### ISSUE TITLE
Error by create monitor - google_alerts.InvalidCredentials: Email or password was incorrect.

### ISSUE THREAD

**Issue by itsecforu** [9b/google-alerts#16]
Hello! 
OS: ubuntu 16.04.

I tried to add email and password:
`$ google-alerts setup --email email@domain.ru --password 'passdw
`
next i run create command and get error :-(.

Tryied with my deffrent emails .

```
$ google-alerts create --term "hello world" --delivery 'rss' --frequency 'realtime'
Traceback (most recent call last):
  File "/usr/local/bin/google-alerts", line 9, in <module>
    load_entry_point('google-alerts==0.2.0', 'console_scripts', 'google-alerts')()
  File "/usr/local/lib/python2.7/dist-packages/google_alerts-0.2.0-py2.7.egg/google_alerts/cli/manage.py", line 146, in main
    ga.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/google_alerts-0.2.0-py2.7.egg/google_alerts/__init__.py", line 298, in authenticate
    raise InvalidCredentials("Email or password was incorrect.")
google_alerts.InvalidCredentials: Email or password was incorrect.
```

**Comment by 9b** [comment]
Please use the seed method. 

https://github.com/9b/google-alerts/wiki/Authentication-Flows

**Comment by 9b** [comment]
It's whatever email you use for Google Alerts.
