### ISSUE TITLE
Dict KeyError when running within script

### ISSUE THREAD

**Issue by p4lsec** [9b/google-alerts#24]
When I attempt to run a script, and when it gets to `ga.create('Google', ({'delivery': 'mail'})`, I get the following error:

`Traceback (most recent call last):
  File "C:\Users\user\Downloads\gAlertsFormatter.py", line 38, in <module>
    ga.create(line, {'delivery': 'MAIL'})
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\google_alerts\__init__.py", line 367, in create
    payload = self._build_payload(term, options)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\google_alerts\__init__.py", line 260, in _build_payload
    if options['alert_frequency'] == 'AT_MOST_ONCE_A_DAY':
KeyError: 'alert_frequency'
[Finished in 2.2s]`

I can authenticate properly, and can create an alert from the command line.  

I have tried to add `'alert_frequency': 'AT_MOST_ONCE_A_DAY'` and `'alert_frequency': 'as_it_happens'` within the dictionary with no luck.  I'm on Windows 10, and I have updated the repository.  Any ideas?  Thanks in advance!

**Comment by 9b** [comment]
Fixed with 9941d20cb063653274d118f6271c7e6bc76c9c9f.

**Comment by p4lsec** [comment]
Thanks for your quick work!
