### ISSUE TITLE
Invalid state error (bis)

### ISSUE THREAD

**Issue by zak-dc** [9b/google-alerts#35]
Hello @9b , 

I have the same invalid state error issue that has been discussed in #5, #20 and #33, even after following the full authentication flow (seeding with chromedriver).

Seeding looks ok :
```
(venv) D:\X>google-alerts seed -d D:/chromedriver.exe
←[1;32mDEBUG __init__:_config_bootstrap():156 2021-02-22 09:14:54,433←[0m| Caching authentication in config file
[...]
[*] Filled in password and submitted.
[!] Waiting for the authentication cookie or 20 seconds
[$] Session has been seeded, google-alerts is ready for use.
```
Create an alert in the terminal does not work:
```
(venv) D:\x>google-alerts create --term "test 3" --delivery mail --frequency realtime
←[1;32mDEBUG __init__:_config_bootstrap():156 2021-02-22 09:17:36,848←[0m| Caching authentication in config file
←[1;32mDEBUG __init__:_session_check():185 2021-02-22 09:17:36,869←[0m| Loaded cookies from session file
←[1;32mDEBUG __init__:_process_state():225 2021-02-22 09:17:37,640←[0m| Capturing state from the request
←[1;32mDEBUG __init__:authenticate():291 2021-02-22 09:17:38,390←[0m| [!] User has already authenticated
Traceback (most recent call last):
  File "C:\x\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\x\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\x\venv\Scripts\google-alerts.exe\__main__.py", line 7, in <module>
  File "d:\x\venv\lib\site-packages\google_alerts\cli\manage.py", line 177, in main
    'exact': args.exact})
  File "d:\x\venv\lib\site-packages\google_alerts\__init__.py", line 367, in create
    raise InvalidState("State was not properly obtained from the app")
google_alerts.InvalidState: State was not properly obtained from the app
```
Accessing the list of alerts neither:
```
DEBUG __init__:_config_bootstrap():156 2021-02-22 09:41:18,735| Caching authentication in config file
DEBUG __init__:_session_check():185 2021-02-22 09:41:18,736| Loaded cookies from session file
DEBUG __init__:_process_state():225 2021-02-22 09:41:19,350| Capturing state from the request
DEBUG __init__:authenticate():291 2021-02-22 09:41:20,140| [!] User has already authenticated
Traceback (most recent call last):
  File "D:/x/Test1.py", line 13, in <module>
    ga.list()
  File "D:\x\venv\lib\site-packages\google_alerts\__init__.py", line 333, in list
    raise InvalidState("State was not properly obtained from the app")
google_alerts.InvalidState: State was not properly obtained from the app

Process finished with exit code 1
```

Thanks in advance for your help and for maintaining this repo, and happy to provide further elements if needed.

Zak

**Comment by zak-dc** [comment]
I may have resolve this issue...
I had the library downloaded from my IDE (Pycharm), with no "requirements.txt" attached, so I was missing many packages.
With all the packages from requirements, it works fine.
