### ISSUE TITLE
Failed to create monitor: Error 500

### ISSUE THREAD

**Issue by sergiopedrazaags** [9b/google-alerts#44]
Hi, tried creating the basic hello world alert in the examples using the command console in Ubuntu --> google-alerts create --term "hello world" --delivery 'rss' --frequency 'realtime'

And got this:

```
DEBUG __init__:_config_bootstrap():156 2021-12-10 05:52:09,046| Caching authentication in config file
DEBUG __init__:_session_check():185 2021-12-10 05:52:09,048| Loaded cookies from session file
DEBUG __init__:_process_state():225 2021-12-10 05:52:09,387| Capturing state from the request
DEBUG __init__:_process_state():235 2021-12-10 05:52:10,773| State value set: [None, [None, None, [None, u'com', [u'en', u'US']], None, 3, [[1, u'', [None, 5], 2, u'en-US', None, None, None, None, None, u'0', None, None, u'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], u'', None, None, [[[None, None, 2]]]]
DEBUG __init__:authenticate():291 2021-12-10 05:52:10,774| [!] User has already authenticated
DEBUG __init__:create():373 2021-12-10 05:52:10,774| Creating alert using: https://www.google.com/alerts/create?x=
Traceback (most recent call last):
  File "/usr/local/bin/google-alerts", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/google_alerts/cli/manage.py", line 177, in main
    'exact': args.exact})
  File "/usr/local/lib/python2.7/dist-packages/google_alerts/__init__.py", line 380, in create
    % response.content)
google_alerts.ActionError: Failed to create monitor: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 500 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>500.</b> <ins>That’s an error.</ins>
  <p>The server encountered an error and could not complete your request.<p>If the problem persists, please <A HREF="http://www.google.com/support/">report</A> your problem and mention this error message and the query that caused it.  <ins>That’s all we know.</ins>
```

Does anyone know what's wrong? The credentials are okay, it even says that the user is already authenticated. Please, advice.

Thank you.

**Comment by sergiopedrazaags** [comment]
Hi, does anyone know what's wrong?

**Comment by sergiopedrazaags** [comment]
Hi, does anyone know what's wrong or is having any issues at all?

**Comment by sergiopedrazaags** [comment]
Hi! Isn't this monitored anymore?

**Comment by 9b** [comment]
I do not have the time to maintain this. Sorry.
