### ISSUE TITLE
While running below command getting an error

### ISSUE THREAD

**Issue by achuta9** [9b/google-alerts#50]
Tried running the below commands getting an error
google-alerts seed --driver c:\python311\google_alerts\chromedriver --timeout 60
or 
google-alerts seed --driver /tmp/chromedriver --timeout 60

DEBUG __init__:_config_bootstrap():158 2023-06-21 20:51:50,878| Caching authentication in config file
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python311\Scripts\google-alerts.exe\__main__.py", line 7, in <module>
  File "C:\python311\google_alerts\cli\manage.py", line 125, in main
    with contextlib.closing(webdriver.Chrome(args.driver, options=chrome_options)) as driver:
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got multiple values for argument 'options'

Can you suggest what is wrong with the command or chrome driver version?

**Comment by mertdeveci5** [comment]
I think this is not being worked on anymore

**Comment by wastu01** [comment]
so sad
